[:program,
 [[:class,
   [:const_ref, [:@const, "Hello", [1, 6]]],
   nil,
   [:bodystmt,
    [[:void_stmt],
     [:def,
      [:@ident, "world_wave", [2, 6]],
      [:params, nil, nil, nil, nil, nil, nil, nil],
      [:bodystmt,
       [[:string_literal,
         [:string_content, [
          :@tstring_content, "good bye👋", [3, 5]]]
        ]],
       nil,
       nil,
       nil]]],
    nil,
    nil,
    nil]]]]
